menu:
    博客: /
    归档: /archives/
    微信: https://mp.weixin.qq.com/s?__biz=MzUzMTcxNTc3Nw==&mid=2247483866&idx=1&sn=a6bc510b08775d8ce81bd84a3bb30bbc
    关于: /about

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-92598519-7

# Copyright Infomation
startyear: 2018
